apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mms-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:kirtanjbhatt/mms-greetings.git
    targetRevision: HEAD
    path: deploy/dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: mms-apps

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true