apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mms-greetings
  namespace: mms-apps
spec:
  encryptedData:
    greetings-message: AgCnhXxUPALWuKYHB81/dNl7XvMXNoiQErYJUgZeTY0EvQ01NoY31qhzCwQNo1v51d5l/u5roQzGGg23B02AjnuGXCDfMiO9VqFcbS4IKq0ybMd4MAoUVzj8rKTvRkAMLkjRqAzRIX+oJWACBX57r7ju+iuTxphRg6k3cpWcE9N909hQA3Yd4VA4M0ILzmkwRF0kqbQvkR5jNVOxhBZ1AX3RyxoT2T8MCqRJ9Jobt6T6uqqV8F808tWar2b8k2uy0t4ZbqgtOIuyKb6wjeq/xluiOdogUvL7zAxEC9SIfuuqv61Ec7v7tykxaO+sw741LmVBBCdVQ1um+hS2wdo3JY4WKPf3hPx1peqZGEL/AZiHjb6r25d5afke5unYEOrxSPfpEZDmKFAUqoJ0sPkVZhOgMvv67hC395X5PvxkKVuP9zIPenYAt6reYJzUmJUBcNb4+5nb0ZrBe49+VbhRnV5CKHzMaSWYmP3CkLmW5KtycutlGafPKnd9LBNg94dm/I0oKJDI8TYK5JobUWioEMu+KyW1hkVAaZ2sN9Atn4g8ev20HsFtygXq7ukU4VAnbhbZhOm6R1LtgPZ6u/dgpPYGi5h4XKvAtSi1GmPXJ1btkDo++izt7OkWRtJAXQVTSlzXhVjypFZI1FOnaGytmiLMc/swS4xiDYHKqTskaF1fiUHzvpW6WvzaRtECxjgYNNQgO8HVfbN28GgsuQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mms-greetings
      namespace: mms-apps