apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mms-greetings
  namespace: mms-apps
spec:
  encryptedData:
    greetings-message: AgAg24rv6k+Vb82oIfIUL6vJhOeFR/P52KKSCITTz4gulqqzTgNth45kI/55Yi5K8UbE0JKonW287xDCsw8nR8rhblldWFwk3k/AryjUuJDYkmQKSnUTUTDhGoyH2qlwG9m6mMMT83ua1tgtmW7x4GqSM5t5kf5V8xAx0Uq+o0VvKsJBrQbZqJUXeYYV3TWW6RfnE6rDMcMVrNUSRhHgFpksJhiIwSLvvq3xtyvVpDVq3hZWPfQr1DwntAbv49NPkTowqZn6Dc6FjR+PlWKbkw9/wQ2+Z9GIMcFEiObKjLzgbUL/WzBLKG+J/DkkTUJju22lQvROuFtWFNPKf72cXtb0SQnFH+QSfXbI3WEUBvTgQyWNhtLLa7yDX1rB69uI3SIcQ5jprorvciS4W2CQXZIaLPKwbM26Q6dJZVpaMcTJEZXrFNhjdjAe8Du1CGd5MDhI37BfEVhNOEjWFR3EZ5GSh9aC937dG6wEAIsRB6V6JuBlhG2I/EOC7EbI+nzAxZs7s5fdxoS7yMh+A44dQ0pTldySYMpTNr3QS/r2t2o2AQeyLjtrXGZii2zsnbIpG8gdgQcIhIqyFJrZw1Dgdw7mUaoUZZYnjIMu4KQTGIHttQJzOtS3I1cuoz6E2XLet6iQtWuyEgFlZ7+K9ZiCOz3xOpUNOkJaJR3w7SjLXjWdCHEYj0CFTn1RXs8zU1Tfphrh0BpA5qMebThwbMMU
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mms-greetings
      namespace: mms-apps