apiVersion: apps/v1
kind: Deployment
metadata:
  name: mms-greetings
  namespace: mms-apps-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mms-greetings
  template:
    metadata:
      labels:
        app: mms-greetings
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          env:
          - name: MMS_GREETING_MSG
            valueFrom:
              secretKeyRef:
                name: mms-secrets
                key: greetings-message