name: Build and publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'deploy/**'
      - '.github/workflows/promote-pipeline.yaml'

env:
  PROJECT_ID: ${{secrets.MMS_GKE_PROJECT}}
  GREETINGS_MSG: ${{secrets.MMS_GREETING_MSG}}
  GKE_CLUSTER: mms-gke-cluster-01
  GKE_ZONE: us-west1-a
  DEPLOYMENT_NAME: mms-greetings
  IMAGE: mms-greetings-image

jobs:
  setup-build-publish:
    name: Setup Build Publish
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2          

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          
        with:
          service_account_key: ${{secrets.MMS_GKE_SA_KEY}}
          project_id: ${{secrets.MMS_GKE_PROJECT}}

      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker

      - name: Build Docker Image and push to GCR
        run: |-
          # Build a docker container and push it to ECR.

          export TAG=$(git rev-parse --short "$GITHUB_SHA")
          echo "Pushing image to GCR..." + $TAG
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG" .
          echo "::set-output name=image::gcr.io/$PROJECT_ID/$IMAGE:$TAG"
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$TAG"
          
      - name: Commit image tag for deployment
        run: |-        
          cd deploy/dev  
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize        
          export TAG=$(git rev-parse --short "$GITHUB_SHA")
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$TAG
          cat kustomization.yaml
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add kustomization.yaml
          git commit -m "image tag updated: $TAG"
          git push

