name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'deploy/**'

env:
  PROJECT_ID: ${{secrets.MMS_GKE_PROJECT}}
  GREETINGS_MSG: ${{secrets.MMS_GREETING_MSG}}
  GKE_CLUSTER: mms-gke-cluster-01
  GKE_ZONE: us-west1-a
  DEPLOYMENT_NAME: mms-greetings
  IMAGE: mms-greetings-image

jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2          

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          
        with:
          service_account_key: ${{secrets.MMS_GKE_SA_KEY}}
          project_id: ${{secrets.MMS_GKE_PROJECT}}

      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get GKE Credentials
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: True
        run: |-
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Build Docker Image and push to GCR
        run: |-
          # Build a docker container and push it to ECR

          export TAG=$(git rev-parse --short "$GITHUB_SHA")
          echo "Pushing image to GCR..." + $TAG
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$TAG" .
          echo "::set-output name=image::gcr.io/$PROJECT_ID/$IMAGE:$TAG"
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$TAG"

      - name: Set up Kustomize
        run: |-          
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy Image to GKE cluster
        run: |-          
          export TAG=$(git rev-parse --short "$GITHUB_SHA")
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$TAG
          cat kustomization.yaml
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME -n mms-apps
          kubectl get services -o wide -n mms-apps

      - name: Set up Kustomize
        run: |-
          cd deploy/dev
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Commit image tag for deployment
        run: |-          
          export TAG=$(git rev-parse --short "$GITHUB_SHA")          
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$TAG
          git config --global user.email "traingke2023@gmail.com"
          git config --global user.name "Kirtan Bhatt"
          git add kustomization.yaml    
      
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: updated using kustomize

