name: Promote to higher environment
on:
  workflow_run:
    workflows: ["Build and publish"]
    types: [completed]

jobs:
  promote-build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Print the input tag to STDOUT
        run: 
          env
          echo  The image is published