name: Promote to higher environment
on:
  workflow_dispatch:
    inputs:      
      Confirm_Promotion:
        description: 'Promote to production'
        required: true
        type: boolean
      approval_comment:
        description: 'Approval comments'
        required: true
        type: string      
      environment_from:
        description: 'Environment to run tests against'
        type: environment
        required: true
      environment_to:
        description: 'Environment to run tests against'
        type: environment
        required: true
      image_tag:
        description: 'Image tags'
        required: true
        type: string

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.Confirm_Promotion }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The image with tag ${{ inputs.image_tag }} in ${{ inputs.environment_from }} is pushed to ${{ inputs.environment_to }}