name: Promote to higher environment
on:
  push:
    branches:
      - main
    paths:
      - deploy/dev/kustomization.yaml
  workflow_dispatch:
    inputs:      
      Confirm_Promotion:
        description: 'Promote the release?'
        required: true
        type: boolean
      approval_comment:
        description: 'Approval comments'
        required: true
        type: string      
      environment_from:
        description: 'Environment to run tests against'
        type: environment
        required: true
        exclude: prod
      environment_to:
        description: 'Environment to run tests against'
        type: environment
        required: true
        exclude: dev
      image_tag:
        description: 'Image tags'
        required: true
        type: string

env:
  PROJECT_ID: ${{secrets.MMS_GKE_PROJECT}}
  GREETINGS_MSG: ${{secrets.MMS_GREETING_MSG}}
  GKE_CLUSTER: mms-gke-cluster-01
  GKE_ZONE: us-west1-a
  DEPLOYMENT_NAME: mms-greetings
  IMAGE: mms-greetings-image

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.Confirm_Promotion }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The image with tag ${{ inputs.image_tag }} in ${{ inputs.environment_from }} is pushed to ${{ inputs.environment_to }}