name: Promote to higher environment
on:
  push:
    branches:
      - main
    paths:
      - deploy/dev/kustomization.yaml  

env:
  PROJECT_ID: ${{secrets.MMS_GKE_PROJECT}}
  GKE_CLUSTER: mms-gke-cluster-01
  GKE_ZONE: us-west1-a
  DEPLOYMENT_NAME: mms-greetings
  IMAGE: mms-greetings-image

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.Confirm_Promotion }} 
    steps:
      - name: Print the input tag to STDOUT
        run: 
          env
          echo  The image is published